const productsData = [
  {
    id: 1,
    name: "La orgullosa",
    bid: 1200,
    user: "misterioso",
    category: "american",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 2,
    name: "La inquieta",
    bid: 1200,
    user: "misterioso",
    category: "american",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 3,
    name: "La impaciente",
    bid: 1200,
    user: "misterioso",
    category: "american",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 4,
    name: "La amable",
    bid: 1200,
    user: "misterioso",
    category: "american",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 5,
    name: "La timida",
    bid: 1200,
    user: "misterioso",
    category: "american",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 6,
    name: "La seria",
    bid: 1200,
    user: "misterioso",
    category: "american",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 7,
    name: "La maestra",
    bid: 1200,
    user: "misterioso",
    category: "venezolan",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 8,
    name: "La constructora",
    bid: 1200,
    user: "misterioso",
    category: "venezolan",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 9,
    name: "La policia",
    bid: 1200,
    user: "misterioso",
    category: "venezolan",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 10,
    name: "La vaca",
    bid: 1200,
    user: "misterioso",
    category: "venezolan",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 11,
    name: "La rana",
    bid: 1200,
    user: "misterioso",
    category: "venezolan",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 12,
    name: "Papas Cheddar",
    bid: 1200,
    user: "misterioso",
    category: "venezolan",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 13,
    name: "Nuggets",
    bid: 1200,
    user: "misterioso",
    category: "patagonia",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 14,
    name: "La presumida",
    bid: 1200,
    user: "misterioso",
    category: "patagonia",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 15,
    name: "La educada",
    bid: 1200,
    user: "misterioso",
    category: "patagonia",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 16,
    name: "La gruñona",
    bid: 1200,
    user: "misterioso",
    category: "patagonia",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 17,
    name: "La egoista",
    bid: 1200,
    user: "misterioso",
    category: "patagonia",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 18,
    name: "La inquieta",
    bid: 1200,
    user: "misterioso",
    category: "patagonia",
    userImg: "",
    cardImg: "../img/cardimg.jfif",
  },
  {
    id: 19,
    name: "Nuggets",
    bid: 1200,
    user: "misterioso",
    category: "nuggets",
    userImg: "",
    cardImg: "../img/nuggets.jfif",
  },
  {
    id: 20,
    name: "Papas Fritas",
    bid: 1200,
    user: "misterioso",
    category: "papas",
    userImg: "",
    cardImg: "../img/fritas.jfif",
  },
];

const splitProducts = (size) => {
  let dividedProducts = [];

  for (let i = 0; i < productsData.length; i += size) {
    dividedProducts.push(productsData.slice(i, i + size));
  }
  return dividedProducts;
};

const productsController = {
  dividedProducts: splitProducts(6),
  nextProductsIndex: 1,
  productsLimit: splitProducts(6).length,
};
